const char *glb_txt_credits =
"The development of POWDER has been influenced, both directly and\n"
"indirectly, from many sources.\n"
"\n"
"This document is by no means exhaustive.  The release notes for the\n"
"individual versions is likely more complete.\n"
"\n"
"--------------------\n"
":Influential People:\n"
"--------------------\n"
"\n"
"Everyone who has posted on rec.games.roguelike.* while I've\n"
"lurked there :>\n"
"\n"
"---------------\n"
":Bug Reporters:\n"
"---------------\n"
"\n"
"R. Alan Monroe, Gottardo Zancani (Zak), James Parker, Ben Shadwick,\n"
"Lauri Vallo, Casey Robinson, Janne Joensuu, Stu, Igor D. WonderLlama,\n"
"Victor Rehorst, copx, Florian 'The Outrider' Piesche, Andrew Walker,\n"
"Kelly Bailey, Bill (hotpoo), Carsten Brockmann, Alexander (Monsterz), \n"
"PBP, Jorge Gonzalez, Brandon Mullins, Lars Radmacher, Cheese Lottery,\n"
"Andrew Poandl, Syrra, Erik Piper, David Damerell, Clare Boothby, \n"
"Elias Erkamo, Guy Banay, Arthur Littlefield, James (darkspoon), Mark\n"
"Ehlke, Elias Erkamo, Yann Vernier, Fancy Carrot, Richard Quirk, Peter\n"
"Biocini, Akoi Meexx, David Hong, Martin Read, JCM, Brendan, Ben Hjelt,\n"
"Grothias, Kaddar, John Overmars, Ciaran Walsh, Michal Bielinski,\n"
"Kantaphon Tongmee, Rachel Elizabeth Dillon, Matthew Rollins, Rapacity,\n"
"Nick Sabo, Markus Maier, Tomo, Matt, TemporalParadox, wing, Michael\n"
"Brough, Deozaan, elcugo, Zappa Penguin, Colin Pritchard, sparrohawc, Zach\n"
"Firth, R. Dan Henry, Xaintrix, stabwound, Oohara Yuuma, Eilu, Robert,\n"
"Iain McCord, Mark Rushakoff, Korgoth, Malte Helmert, The Rani, Peter\n"
"Roozemaal, Robert Hamaker, FEG, Bridget Farace, David R. Schultz,\n"
"Tobias Pierce, Vladimir Stalin, Narius Varigor, jockmo 42, Cuboidz,\n"
"Meddyan, Stefan O'Rear, Pikadude No. 1, Teun Peelen, Roger Bolton,\n"
"Mikko Karttunen, SparroHawc, Ambvai, Erik Spigel, Joe B, Strange Child,\n"
"Kayvon, Stefan O'Rear, Gwazi01, Will Weinzettl, Johaan Strojandogg,\n"
"Nicholas Young, Lawrence T. Levine, Garron Bailey, Michal Skrzypek,\n"
"Garron, Eris Discordia, Nathan Bogue, Inu, Kender, Mental Mouse,\n"
"Patrick Don't have one, Matt_S, Sam Spencer, Alex Marsh, Robert Barber,\n"
"Mattock, Lorenzo Batallones, Konstantin Stupnik, Paul Nguyen,\n"
"sulai, Claudio, B. Perry, Julian Agloro, Aapo Rantalainen,\n"
"Paul Strickland, Michael Gindt, Mike Ratzlaff, Gurkan Sengun,\n"
"Don Collins.\n"
"\n"
"---------------\n"
":Patch Writers:\n"
"---------------\n"
"\n"
"Richard Quirk, Ciaran Walsh, Marvin Sanchez, Oohara Yuuma, Peter Roozemaal,\n"
"Derek S. Ray, David Parker, Ilya Kasnacheev, Andreas Bohm, Zasenko Sergey,\n"
"Joe Buck, Michael Sterrett, Matthew Wyatt.\n"
"\n"
"-----------------\n"
":Tileset Artists:\n"
"-----------------\n"
"\n"
"Adam Bolt, Akoi Meexx, Andrea Menga, Zak, Kelly Bailey, Markus Maier,\n"
"Ibson the Grey, Chris Lomaka.\n"
"\n"
"---------------\n"
":Special Notes:\n"
"---------------\n"
"\n"
"Adam Bolt: Unsurprisingly, the tiles in the Adam Bolt tileset came\n"
"from Adam Bolt's tileset.\n"
"\n"
"Akoi Meexx: The Akoi Meexx tileset, which is now the default POWDER\n"
"tileset.\n"
"\n"
"Andrea Menga (Widar): The Nethackish Tileset.\n"
"\n"
"Bill Blake: The PS3 Port\n"
"\n"
"Ben Shadwick: Another use for bottles of water, skill level\n"
"notification, and many other valuable suggestions.\n"
"\n"
"Casey Robinson: [Select] to do a one time command on Start menu.\n"
"\n"
"Darshan Shaligram: Character Dump option.\n"
"\n"
"David Parker: Port of POWDER to the GP2X.\n"
"\n"
"Emanuel Schleussinger: Creator of HAM, the library for the GBA that\n"
"made this much, much, easier.\n"
"\n"
"Erik Piper: Numerous UI suggestions for both SDL and GBA versions which \n"
"I used.\n"
"\n"
"Gottardo Zancani (Zak): Binding [L] and [R] buttons.  Cool maps.\n"
"Compiling the Adam Bolt tilesets.\n"
"\n"
"Hansjorg Malthaner: Sunfire Spell.\n"
"\n"
"Ilya Kasnacheev: WinCE port.\n"
"\n"
"Igor D. WonderLlama: Second ascension post on rec.games.roguelike.misc (063).\n"
"\n"
"Jose Ignacio Rodriguez Fernandez: Push to multilingualism.  Reminder\n"
"to invalidate games on death.\n"
"\n"
"Jonathan Buchanan: The Wii Port\n"
"\n"
"Kantaphon Tongmee: Discussion on god code.\n"
"\n"
"Kelly Bailey: The ASCII Tileset.\n"
"\n"
"Lauri Vallo: First [POWDER] post on rec.games.roguelike.misc.  First\n"
"ascension post on rec.games.roguelike.misc.  Inspirational rumours for\n"
"the Blue Dragon Cavern.  Now all I need are fortune cookies of some\n"
"sort...\n"
"\n"
"Markus Maier: Bevy of font redesigns.\n"
"\n"
"Marvin Sanchez: Port of POWDER to PSP.\n"
"\n"
"R. Alan Monroe: Suggestions for UI improvements.  Most of which I\n"
"haven't used, but know that I should.  (One day I'll get around to\n"
"proportional fonts...)\n"
"\n"
"R. Dan Henry: Reminding me the inventory screen is ugly.\n"
"\n"
"Richard Quirk: Submitted (the first) code patches for improved DS\n"
"behaviour.\n"
"\n"
"5parrow: Mouse movement algorithm on rec.games.roguelike.nethack.\n"
"\n"
"Takuji Nishimura and Makoto Matsumoto: The most excellent Mersenne\n"
"Twister.\n"
"\n"
"Tim Jordan: Character sheet improvements.\n"
"\n"
"Magne Groenhuis: Item teleportation.\n"
"\n"
"Victor Rehorst: Requesting better Pogoshell support.\n"
"\n"
"William Franklin: Proper death of Skeletons.\n"
"\n"
"Will Shattuck: Plain text key assignment list.\n"
"\n"
"-------------------\n"
":Influential Games:\n"
"-------------------\n"
"\n"
"Nethack\n"
"\n"
"The first roguelike I played.  POWDER seeks to build a similar world\n"
"of interoperability, where one can say \"The dev team thought of\n"
"everything!\"  Seeks is the operative word here.\n"
"\n"
"ADOM\n"
"\n"
"While my introduction to Nethack was a finished game, I had the chance\n"
"to play ADOM as it evolved.  This gave a good insight into the\n"
"development process.\n"
"\n"
"Crawl\n"
"\n"
"Started POWDER without having played this.  However, when I returned\n"
"to the roguelike newsgroups after many years absence, I found everyone\n"
"talking about Crawl.  From what I've read, for good reasons.  Thus,\n"
"I've read up on spoilers for Crawl, seeking always the key pieces of\n"
"game design that can be lifted into POWDER.  Sticky Flames, for\n"
"example, comes from here.  After playing Crawl for a bit, I also was\n"
"motivated to change the shadow code to highlight LOS.\n"
;
