// dpdf_table.h
// Automagically generated by builddpdf
// DO NOT HAND EDIT.  Yes, this means you.

// Dimensions of table, these are inclusive.
#define DPDF_MAXSIDES 50
#define DPDF_MAXROLLS 5
#define DPDF_SCALE    256

// Since 0 and 1 are obvious for sides, hence the -1
extern const int glb_dpdftable[DPDF_MAXROLLS+1][DPDF_MAXSIDES-1];
