//
// encyclopedia.h
// Automagically Generated by support/encyclopedia2c/encyclopedia2c
//       DO NOT HAND EDIT.
// (Yes, this does mean you!)
//

struct encyclopedia_entry
{
    int          key;
    const char  *name;
    int          numlines;
    const char **lines;
};

struct encyclopedia_book
{
    const char               *bookname;
    int                       numentries;
    const encyclopedia_entry**entries;
};

#define NUM_ENCYCLOPEDIA_BOOKS 12
extern const encyclopedia_book *glb_encyclopedia[NUM_ENCYCLOPEDIA_BOOKS];
