const char *glb_txt_license =
"THE POWDER LICENSE:\n"
"-------------------\n"
"\n"
"POWDER is copyright 2003-2009 by Jeff Lait.\n"
"All rights reserved.\n"
"\n"
"Note\n"
"----\n"
"The Adam Bolt tileset are copyright by Adam Bolt and are licensed\n"
"separately.  Other tilesets are creations of the respective creators -\n"
"download the latest artpack for details.\n"
"\n"
"MSVCP71.DLL and MSVCR71.DLL are owned and licensed entirely by\n"
"Microsoft.  They are redistributed with POWDER as per their edicts.  I'd\n"
"rather not have to include them.\n"
"\n"
"Simple DirectMedia Layer (SDL) library is licensed under the GNU\n"
"Lesser General Public License (LGPL).  POWDER conforms to the third\n"
"clause - where you downloaded this should also have been a link to\n"
"download a source tarball.\n"
"\n"
"Information about SDL can be found at:\n"
"http://www.libsdl.org/\n"
"\n"
"Information about the LGPL license can be found at:\n"
"http://www.libsdl.org/license.php\n"
"http://www.gnu.org.copyleft/lgpl.html\n"
"\n"
"Information about the Mersenne Twister can be found at:\n"
"http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/emt.html\n"
"\n"
"Execution\n"
"---------\n"
"You are allowed to execute the POWDER binary, either by running it in\n"
"an emulator or on hardware.\n"
"\n"
"Duplication\n"
"-----------\n"
"You are allowed to duplicate the POWDER distribution provided you:\n"
"1) Keep the distribution intact.  This means keeping this license.\n"
"2) Do not charge for the act of duplication, nor for the medium of\n"
"duplication above the rate which you paid to acquire it.\n"
"3) Do not add to the distribution in a manner which obscures the\n"
"original author.\n"
"4) Do not modify the POWDER binary nor accompanying files.  This\n"
"includes, but is not limited to, the removal of any licensing or\n"
"copyright information embedded in the files.\n"
"\n"
"An exception is made when duplicating to a cartridge or similar device\n"
"for purpose of executing the binary on hardware.  In this case, the\n"
"binary alone needs to be duplicated (as that is all that is practical)\n"
"An exception is made for patching the binary to run on certain\n"
"platforms.\n"
"\n"
"Transfer\n"
"--------\n"
"You are free to transfer copies of POWDER to others, provided they\n"
"remain unaltered, and the transfer is performed without payment.  You\n"
"are encouraged to instead show people to the author's current web site\n"
"where the latest version may be acquired.\n"
"\n"
"Reverse Engineering\n"
"-------------------\n"
"You are strongly discouraged from reverse engingeering the POWDER\n"
"binary.  If you have questions about how an algorithm worked, contact\n"
"the author who will likely freely answer.  If would like the source,\n"
"check the download site where it is available.\n"
"\n"
"Disclaimer\n"
"----------\n"
"Neither the author, nor anyone associated with the distribution of\n"
"this binary to your system, is responsible for any damage done to your\n"
"computer, console, or handheld.  This includes, but is not limited\n"
"to, loss of data, work, time, or hardware.  \n"
"\n"
"In some, or all, places, a limitation of liability may not be\n"
"possible.  It is your responsibility to verify that within your\n"
"jurisdiction the above disclaimer fully exempts the author from all\n"
"liability.  If it does not, all earlier rights of execution,\n"
"duplication, and transfer are rescinded.\n"
"\n"
"ALL CAPS\n"
"--------\n"
"THIS SECTION OF THE LICENSING AGREEMENT IS WRITTEN IN ALL CAPS TO MAKE\n"
"IT APPEAR MORE LEGAL.  IT ISN'T.  INSTEAD, IT IS JUST A FRIENDLY\n"
"REMINDER TO ENJOY POWDER AND TO CONTACT THE AUTHOR IF YOU PLAY IT.\n"
"EVEN IF YOU HATE THE GAME.  POWDER IS A LABOUR OF LOVE WHICH HAS PAID\n"
"FOR ITSELF IN THE AUTHOR'S OWN ENJOYMENT, YET THERE IS NO REASON WHY\n"
"IT CANNOT EARN EVEN MORE DIVIDENDS OF HAPPINESS BY BRINGING JOY TO THE\n"
"LIVES OF OTHERS.\n"
;
