// Auto-generated .cpp file
// DO NOT HAND EDIT
// Generated by buildrooms.sh
 
#include "../map.h"
#include "belweir.cpp"
#include "circle.cpp"
#include "circle2.cpp"
#include "crypt.cpp"
#include "crypt2.cpp"
#include "crypt3.cpp"
#include "crypt4.cpp"
#include "crypt5.cpp"
#include "daemon1.cpp"
#include "daemon2.cpp"
#include "forest.cpp"
#include "forest2.cpp"
#include "hall.cpp"
#include "hall2.cpp"
#include "hauntedisle.cpp"
#include "hruth.cpp"
#include "isle.cpp"
#include "isle2.cpp"
#include "kiwi.cpp"
#include "klaskov.cpp"
#include "kobold_barrack.cpp"
#include "kobold_hideout.cpp"
#include "lair.cpp"
#include "lair2.cpp"
#include "lava.cpp"
#include "lava2.cpp"
#include "lava3.cpp"
#include "lava4.cpp"
#include "minotaur.cpp"
#include "orc_lair.cpp"
#include "orc_lair2.cpp"
#include "pillar.cpp"
#include "pillar2.cpp"
#include "pillar3.cpp"
#include "poison.cpp"
#include "quizar.cpp"
#include "ratwarren.cpp"
#include "ratwarren2.cpp"
#include "river.cpp"
#include "river2.cpp"
#include "secret.cpp"
#include "slug.cpp"
#include "slug2.cpp"
#include "sokoban.cpp"
#include "sokoban2.cpp"
#include "spiral.cpp"
#include "temple.cpp"
#include "temple2.cpp"
#include "tridude.cpp"
#include "tridude2.cpp"
#include "tridude3.cpp"
#include "tridude4.cpp"
#include "troll.cpp"
#include "troll2.cpp"
#include "troll3.cpp"
#include "turtloid_pond.cpp"
#include "turtloid_pond2.cpp"
#include "tutorial.cpp"
#include "vault.cpp"
#include "vault2.cpp"
#include "vault3.cpp"
#include "vault4.cpp"
#include "why.cpp"
#include "zoo.cpp"
#include "zoo2.cpp"
#include "zoo3.cpp"
#include "zoo4.cpp"
#include "zoo5.cpp"
 
const ROOM_DEF *glb_allroomdefs[68+1] =
{
	&glb_belweir_roomdef,
	&glb_circle_roomdef,
	&glb_circle2_roomdef,
	&glb_crypt_roomdef,
	&glb_crypt2_roomdef,
	&glb_crypt3_roomdef,
	&glb_crypt4_roomdef,
	&glb_crypt5_roomdef,
	&glb_daemon1_roomdef,
	&glb_daemon2_roomdef,
	&glb_forest_roomdef,
	&glb_forest2_roomdef,
	&glb_hall_roomdef,
	&glb_hall2_roomdef,
	&glb_hauntedisle_roomdef,
	&glb_hruth_roomdef,
	&glb_isle_roomdef,
	&glb_isle2_roomdef,
	&glb_kiwi_roomdef,
	&glb_klaskov_roomdef,
	&glb_kobold_barrack_roomdef,
	&glb_kobold_hideout_roomdef,
	&glb_lair_roomdef,
	&glb_lair2_roomdef,
	&glb_lava_roomdef,
	&glb_lava2_roomdef,
	&glb_lava3_roomdef,
	&glb_lava4_roomdef,
	&glb_minotaur_roomdef,
	&glb_orc_lair_roomdef,
	&glb_orc_lair2_roomdef,
	&glb_pillar_roomdef,
	&glb_pillar2_roomdef,
	&glb_pillar3_roomdef,
	&glb_poison_roomdef,
	&glb_quizar_roomdef,
	&glb_ratwarren_roomdef,
	&glb_ratwarren2_roomdef,
	&glb_river_roomdef,
	&glb_river2_roomdef,
	&glb_secret_roomdef,
	&glb_slug_roomdef,
	&glb_slug2_roomdef,
	&glb_sokoban_roomdef,
	&glb_sokoban2_roomdef,
	&glb_spiral_roomdef,
	&glb_temple_roomdef,
	&glb_temple2_roomdef,
	&glb_tridude_roomdef,
	&glb_tridude2_roomdef,
	&glb_tridude3_roomdef,
	&glb_tridude4_roomdef,
	&glb_troll_roomdef,
	&glb_troll2_roomdef,
	&glb_troll3_roomdef,
	&glb_turtloid_pond_roomdef,
	&glb_turtloid_pond2_roomdef,
	&glb_tutorial_roomdef,
	&glb_vault_roomdef,
	&glb_vault2_roomdef,
	&glb_vault3_roomdef,
	&glb_vault4_roomdef,
	&glb_why_roomdef,
	&glb_zoo_roomdef,
	&glb_zoo2_roomdef,
	&glb_zoo3_roomdef,
	&glb_zoo4_roomdef,
	&glb_zoo5_roomdef,
	0
};
