// Auto-generated .map file
// DO NOT HAND EDIT
// Generated from crypt2.map

#include "../map.h"
#include "../glbdef.h"

const SQUARE_NAMES glb_crypt2_squarelist[] =
{
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_BLOCKEDDOOR,	SQUARE_CORRIDOR,	SQUARE_WALL,	
SQUARE_CORRIDOR,	SQUARE_WALL,	SQUARE_CORRIDOR,	SQUARE_WALL,	
SQUARE_CORRIDOR,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_CORRIDOR,	
SQUARE_WALL,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_WALL,	SQUARE_CORRIDOR,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_BLOCKEDDOOR,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_BLOCKEDDOOR,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_BLOCKEDDOOR,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL
};

const PT2 glb_crypt2_moblist[] =
{
	{ 7, 5, MOB_ZOMBIE },
	{ 2, 5, MOB_ZOMBIE },
	{ 7, 3, MOB_SKELETON },
	{ 3, 3, MOB_ZOMBIE },
	{ 7, 2, MOB_ZOMBIE },
	{ 4, 2, MOB_GHAST },
	{ 7, 1, MOB_SKELETON },
	{ 5, 1, MOB_ZOMBIE },
	{ 3, 1, MOB_ZOMBIE },
	{ 1, 1, MOB_ZOMBIE },
	{ -1, -1, MOB_NONE }
};

const PT2 glb_crypt2_itemlist[] =
{
	{ -1, -1, ITEM_NONE }
};

const PT2 glb_crypt2_itemtypelist[] =
{
	{ 4, 2, ITEMTYPE_ARMOUR },
	{ -1, -1, ITEMTYPE_NONE }
};

const PT2 glb_crypt2_moblevellist[] =
{
	{ -1, -1, MOBLEVEL_NONE }
};

const PT2 glb_crypt2_intrinsiclist[] =
{
	{ -1, -1, INTRINSIC_NONE }
};

const PT2 glb_crypt2_squareflaglist[] =
{
	{ 8, 6, SQUAREFLAG_LIT },
	{ 7, 6, SQUAREFLAG_LIT },
	{ 6, 6, SQUAREFLAG_LIT },
	{ 5, 6, SQUAREFLAG_LIT },
	{ 4, 6, SQUAREFLAG_LIT },
	{ 3, 6, SQUAREFLAG_LIT },
	{ 2, 6, SQUAREFLAG_LIT },
	{ 1, 6, SQUAREFLAG_LIT },
	{ 0, 6, SQUAREFLAG_LIT },
	{ 8, 5, SQUAREFLAG_LIT },
	{ 7, 5, SQUAREFLAG_LIT },
	{ 6, 5, SQUAREFLAG_LIT },
	{ 5, 5, SQUAREFLAG_LIT },
	{ 4, 5, SQUAREFLAG_LIT },
	{ 3, 5, SQUAREFLAG_LIT },
	{ 2, 5, SQUAREFLAG_LIT },
	{ 1, 5, SQUAREFLAG_LIT },
	{ 0, 5, SQUAREFLAG_LIT },
	{ 8, 4, SQUAREFLAG_LIT },
	{ 7, 4, SQUAREFLAG_LIT },
	{ 6, 4, SQUAREFLAG_LIT },
	{ 5, 4, SQUAREFLAG_LIT },
	{ 4, 4, SQUAREFLAG_LIT },
	{ 3, 4, SQUAREFLAG_LIT },
	{ 2, 4, SQUAREFLAG_LIT },
	{ 1, 4, SQUAREFLAG_LIT },
	{ 0, 4, SQUAREFLAG_LIT },
	{ 8, 3, SQUAREFLAG_LIT },
	{ 7, 3, SQUAREFLAG_LIT },
	{ 6, 3, SQUAREFLAG_LIT },
	{ 5, 3, SQUAREFLAG_LIT },
	{ 4, 3, SQUAREFLAG_LIT },
	{ 3, 3, SQUAREFLAG_LIT },
	{ 2, 3, SQUAREFLAG_LIT },
	{ 1, 3, SQUAREFLAG_LIT },
	{ 0, 3, SQUAREFLAG_LIT },
	{ 8, 2, SQUAREFLAG_LIT },
	{ 7, 2, SQUAREFLAG_LIT },
	{ 6, 2, SQUAREFLAG_LIT },
	{ 5, 2, SQUAREFLAG_LIT },
	{ 4, 2, SQUAREFLAG_LIT },
	{ 3, 2, SQUAREFLAG_LIT },
	{ 2, 2, SQUAREFLAG_LIT },
	{ 1, 2, SQUAREFLAG_LIT },
	{ 0, 2, SQUAREFLAG_LIT },
	{ 8, 1, SQUAREFLAG_LIT },
	{ 7, 1, SQUAREFLAG_LIT },
	{ 6, 1, SQUAREFLAG_LIT },
	{ 5, 1, SQUAREFLAG_LIT },
	{ 4, 1, SQUAREFLAG_LIT },
	{ 3, 1, SQUAREFLAG_LIT },
	{ 2, 1, SQUAREFLAG_LIT },
	{ 1, 1, SQUAREFLAG_LIT },
	{ 0, 1, SQUAREFLAG_LIT },
	{ 8, 0, SQUAREFLAG_LIT },
	{ 7, 0, SQUAREFLAG_LIT },
	{ 6, 0, SQUAREFLAG_LIT },
	{ 5, 0, SQUAREFLAG_LIT },
	{ 4, 0, SQUAREFLAG_LIT },
	{ 3, 0, SQUAREFLAG_LIT },
	{ 2, 0, SQUAREFLAG_LIT },
	{ 1, 0, SQUAREFLAG_LIT },
	{ 0, 0, SQUAREFLAG_LIT },
	{ -1, -1, SQUAREFLAG_NONE }
};

const PT2 glb_crypt2_signpostlist[] =
{
	{ -1, -1, SIGNPOST_NONE }
};

const ROOM_DEF glb_crypt2_roomdef =
{
	{ 9, 7, 0 },
	glb_crypt2_squarelist,
	glb_crypt2_squareflaglist,
	glb_crypt2_itemlist,
	glb_crypt2_moblist,
	glb_crypt2_itemtypelist,
	glb_crypt2_moblevellist,
	glb_crypt2_intrinsiclist,
	glb_crypt2_signpostlist,
	2, -1,
	100,
	0, 0,
	0,
	1,
	1,
	1,
	1,
	-1, -1, 
	-1, 
	"crypt2"
};
