// Auto-generated .map file
// DO NOT HAND EDIT
// Generated from isle2.map

#include "../map.h"
#include "../glbdef.h"

const SQUARE_NAMES glb_isle2_squarelist[] =
{
SQUARE_EMPTY,	SQUARE_WATER,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_WATER,	SQUARE_WATER,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_WATER,	SQUARE_WATER,	SQUARE_DOOR,	
SQUARE_WATER,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_WATER,	SQUARE_WATER,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_WATER,	SQUARE_WATER,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_WATER,	SQUARE_WATER,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_WATER,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_WATER,	SQUARE_WATER,	SQUARE_EMPTY,	SQUARE_WATER,	
SQUARE_WATER,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_WATER,	
SQUARE_DOOR,	SQUARE_CORRIDOR,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_WATER,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_WATER,	
SQUARE_WATER,	SQUARE_WATER,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_DOOR,	SQUARE_WATER,	SQUARE_WATER,	
SQUARE_WATER,	SQUARE_WATER,	SQUARE_EMPTY,	SQUARE_EMPTY
};

const PT2 glb_isle2_moblist[] =
{
	{ -1, -1, MOB_NONE }
};

const PT2 glb_isle2_itemlist[] =
{
	{ -1, -1, ITEM_NONE }
};

const PT2 glb_isle2_itemtypelist[] =
{
	{ 6, 5, ITEMTYPE_ANY },
	{ 5, 5, ITEMTYPE_ANY },
	{ 5, 2, ITEMTYPE_ANY },
	{ 4, 2, ITEMTYPE_ANY },
	{ -1, -1, ITEMTYPE_NONE }
};

const PT2 glb_isle2_moblevellist[] =
{
	{ 6, 5, MOBLEVEL_NORMAL },
	{ 5, 5, MOBLEVEL_NORMAL },
	{ 5, 2, MOBLEVEL_NORMAL },
	{ 4, 2, MOBLEVEL_NORMAL },
	{ -1, -1, MOBLEVEL_NONE }
};

const PT2 glb_isle2_intrinsiclist[] =
{
	{ -1, -1, INTRINSIC_NONE }
};

const PT2 glb_isle2_squareflaglist[] =
{
	{ 7, 7, SQUAREFLAG_LIT },
	{ 6, 7, SQUAREFLAG_LIT },
	{ 5, 7, SQUAREFLAG_LIT },
	{ 4, 7, SQUAREFLAG_LIT },
	{ 3, 7, SQUAREFLAG_LIT },
	{ 9, 6, SQUAREFLAG_LIT },
	{ 8, 6, SQUAREFLAG_LIT },
	{ 7, 6, SQUAREFLAG_LIT },
	{ 6, 6, SQUAREFLAG_LIT },
	{ 5, 6, SQUAREFLAG_LIT },
	{ 4, 6, SQUAREFLAG_LIT },
	{ 3, 6, SQUAREFLAG_LIT },
	{ 2, 6, SQUAREFLAG_LIT },
	{ 1, 6, SQUAREFLAG_LIT },
	{ 0, 6, SQUAREFLAG_LIT },
	{ 9, 5, SQUAREFLAG_LIT },
	{ 8, 5, SQUAREFLAG_LIT },
	{ 7, 5, SQUAREFLAG_LIT },
	{ 6, 5, SQUAREFLAG_LIT },
	{ 5, 5, SQUAREFLAG_LIT },
	{ 4, 5, SQUAREFLAG_LIT },
	{ 3, 5, SQUAREFLAG_LIT },
	{ 2, 5, SQUAREFLAG_LIT },
	{ 1, 5, SQUAREFLAG_LIT },
	{ 9, 4, SQUAREFLAG_LIT },
	{ 8, 4, SQUAREFLAG_LIT },
	{ 7, 4, SQUAREFLAG_LIT },
	{ 6, 4, SQUAREFLAG_LIT },
	{ 5, 4, SQUAREFLAG_LIT },
	{ 4, 4, SQUAREFLAG_LIT },
	{ 3, 4, SQUAREFLAG_LIT },
	{ 2, 4, SQUAREFLAG_LIT },
	{ 1, 4, SQUAREFLAG_LIT },
	{ 0, 4, SQUAREFLAG_LIT },
	{ 9, 3, SQUAREFLAG_LIT },
	{ 8, 3, SQUAREFLAG_LIT },
	{ 7, 3, SQUAREFLAG_LIT },
	{ 6, 3, SQUAREFLAG_LIT },
	{ 5, 3, SQUAREFLAG_LIT },
	{ 4, 3, SQUAREFLAG_LIT },
	{ 3, 3, SQUAREFLAG_LIT },
	{ 2, 3, SQUAREFLAG_LIT },
	{ 1, 3, SQUAREFLAG_LIT },
	{ 0, 3, SQUAREFLAG_LIT },
	{ 9, 2, SQUAREFLAG_LIT },
	{ 8, 2, SQUAREFLAG_LIT },
	{ 7, 2, SQUAREFLAG_LIT },
	{ 6, 2, SQUAREFLAG_LIT },
	{ 5, 2, SQUAREFLAG_LIT },
	{ 4, 2, SQUAREFLAG_LIT },
	{ 3, 2, SQUAREFLAG_LIT },
	{ 2, 2, SQUAREFLAG_LIT },
	{ 1, 2, SQUAREFLAG_LIT },
	{ 0, 2, SQUAREFLAG_LIT },
	{ 9, 1, SQUAREFLAG_LIT },
	{ 8, 1, SQUAREFLAG_LIT },
	{ 7, 1, SQUAREFLAG_LIT },
	{ 6, 1, SQUAREFLAG_LIT },
	{ 5, 1, SQUAREFLAG_LIT },
	{ 4, 1, SQUAREFLAG_LIT },
	{ 3, 1, SQUAREFLAG_LIT },
	{ 2, 1, SQUAREFLAG_LIT },
	{ 1, 1, SQUAREFLAG_LIT },
	{ 0, 1, SQUAREFLAG_LIT },
	{ 7, 0, SQUAREFLAG_LIT },
	{ 6, 0, SQUAREFLAG_LIT },
	{ 5, 0, SQUAREFLAG_LIT },
	{ 4, 0, SQUAREFLAG_LIT },
	{ 3, 0, SQUAREFLAG_LIT },
	{ 2, 0, SQUAREFLAG_LIT },
	{ 1, 0, SQUAREFLAG_LIT },
	{ -1, -1, SQUAREFLAG_NONE }
};

const PT2 glb_isle2_signpostlist[] =
{
	{ -1, -1, SIGNPOST_NONE }
};

const ROOM_DEF glb_isle2_roomdef =
{
	{ 10, 8, 0 },
	glb_isle2_squarelist,
	glb_isle2_squareflaglist,
	glb_isle2_itemlist,
	glb_isle2_moblist,
	glb_isle2_itemtypelist,
	glb_isle2_moblevellist,
	glb_isle2_intrinsiclist,
	glb_isle2_signpostlist,
	4, -1,
	100,
	0, 0,
	0,
	1,
	1,
	1,
	1,
	-1, -1, 
	-1, 
	"isle2"
};
