// Auto-generated .map file
// DO NOT HAND EDIT
// Generated from lair.map

#include "../map.h"
#include "../glbdef.h"

const SQUARE_NAMES glb_lair_squarelist[] =
{
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_EMPTY,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_EMPTY,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_CORRIDOR,	
SQUARE_EMPTY,	SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_WALL,	SQUARE_EMPTY,	SQUARE_WALL,	SQUARE_FLOOR,	
SQUARE_SECRETDOOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_SECRETDOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_SECRETDOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_EMPTY,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_EMPTY,	
SQUARE_CORRIDOR,	SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_WALL,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_CORRIDOR,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY
};

const PT2 glb_lair_moblist[] =
{
	{ 10, 4, MOB_BLUEDRAGON },
	{ 11, 3, MOB_BLUEDRAGON },
	{ 10, 2, MOB_BLUEDRAGON },
	{ -1, -1, MOB_NONE }
};

const PT2 glb_lair_itemlist[] =
{
	{ 11, 2, ITEM_REFLECTSHIELD },
	{ -1, -1, ITEM_NONE }
};

const PT2 glb_lair_itemtypelist[] =
{
	{ -1, -1, ITEMTYPE_NONE }
};

const PT2 glb_lair_moblevellist[] =
{
	{ -1, -1, MOBLEVEL_NONE }
};

const PT2 glb_lair_intrinsiclist[] =
{
	{ -1, -1, INTRINSIC_NONE }
};

const PT2 glb_lair_squareflaglist[] =
{
	{ 12, 5, SQUAREFLAG_LIT },
	{ 11, 5, SQUAREFLAG_LIT },
	{ 10, 5, SQUAREFLAG_LIT },
	{ 9, 5, SQUAREFLAG_LIT },
	{ 8, 5, SQUAREFLAG_LIT },
	{ 7, 5, SQUAREFLAG_LIT },
	{ 6, 5, SQUAREFLAG_LIT },
	{ 5, 5, SQUAREFLAG_LIT },
	{ 12, 4, SQUAREFLAG_LIT },
	{ 11, 4, SQUAREFLAG_LIT },
	{ 10, 4, SQUAREFLAG_LIT },
	{ 9, 4, SQUAREFLAG_LIT },
	{ 8, 4, SQUAREFLAG_LIT },
	{ 7, 4, SQUAREFLAG_LIT },
	{ 6, 4, SQUAREFLAG_LIT },
	{ 5, 4, SQUAREFLAG_LIT },
	{ 2, 4, SQUAREFLAG_LIT },
	{ 1, 4, SQUAREFLAG_LIT },
	{ 0, 4, SQUAREFLAG_LIT },
	{ 12, 3, SQUAREFLAG_LIT },
	{ 11, 3, SQUAREFLAG_LIT },
	{ 10, 3, SQUAREFLAG_LIT },
	{ 9, 3, SQUAREFLAG_LIT },
	{ 8, 3, SQUAREFLAG_LIT },
	{ 7, 3, SQUAREFLAG_LIT },
	{ 6, 3, SQUAREFLAG_LIT },
	{ 5, 3, SQUAREFLAG_LIT },
	{ 2, 3, SQUAREFLAG_LIT },
	{ 1, 3, SQUAREFLAG_LIT },
	{ 0, 3, SQUAREFLAG_LIT },
	{ 12, 2, SQUAREFLAG_LIT },
	{ 11, 2, SQUAREFLAG_LIT },
	{ 10, 2, SQUAREFLAG_LIT },
	{ 9, 2, SQUAREFLAG_LIT },
	{ 8, 2, SQUAREFLAG_LIT },
	{ 7, 2, SQUAREFLAG_LIT },
	{ 6, 2, SQUAREFLAG_LIT },
	{ 5, 2, SQUAREFLAG_LIT },
	{ 2, 2, SQUAREFLAG_LIT },
	{ 1, 2, SQUAREFLAG_LIT },
	{ 0, 2, SQUAREFLAG_LIT },
	{ 12, 1, SQUAREFLAG_LIT },
	{ 11, 1, SQUAREFLAG_LIT },
	{ 10, 1, SQUAREFLAG_LIT },
	{ 9, 1, SQUAREFLAG_LIT },
	{ 8, 1, SQUAREFLAG_LIT },
	{ 7, 1, SQUAREFLAG_LIT },
	{ 6, 1, SQUAREFLAG_LIT },
	{ 5, 1, SQUAREFLAG_LIT },
	{ -1, -1, SQUAREFLAG_NONE }
};

const PT2 glb_lair_signpostlist[] =
{
	{ -1, -1, SIGNPOST_NONE }
};

const ROOM_DEF glb_lair_roomdef =
{
	{ 14, 7, 0 },
	glb_lair_squarelist,
	glb_lair_squareflaglist,
	glb_lair_itemlist,
	glb_lair_moblist,
	glb_lair_itemtypelist,
	glb_lair_moblevellist,
	glb_lair_intrinsiclist,
	glb_lair_signpostlist,
	-1, -1,
	100,
	0, 0,
	0,
	1,
	1,
	1,
	1,
	-1, -1, 
	-1, 
	"lair"
};
