// Auto-generated .map file
// DO NOT HAND EDIT
// Generated from lava4.map

#include "../map.h"
#include "../glbdef.h"

const SQUARE_NAMES glb_lava4_squarelist[] =
{
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_BLOCKEDDOOR,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_BLOCKEDDOOR,	
SQUARE_BLOCKEDDOOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_EMPTY,	
SQUARE_CORRIDOR,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_LAVA,	SQUARE_LAVA,	SQUARE_LAVA,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_LAVA,	SQUARE_LAVA,	SQUARE_LAVA,	
SQUARE_LAVA,	SQUARE_LAVA,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_LAVA,	SQUARE_LAVA,	SQUARE_LAVA,	
SQUARE_LAVA,	SQUARE_LAVA,	SQUARE_LAVA,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_LAVA,	
SQUARE_LAVA,	SQUARE_CORRIDOR,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY
};

const PT2 glb_lava4_moblist[] =
{
	{ 5, 6, MOB_REDDRAGON },
	{ 5, 5, MOB_REDDRAGON },
	{ 4, 5, MOB_REDDRAGON },
	{ 3, 5, MOB_REDDRAGON },
	{ 1, 4, MOB_REDDRAGON },
	{ -1, -1, MOB_NONE }
};

const PT2 glb_lava4_itemlist[] =
{
	{ -1, -1, ITEM_NONE }
};

const PT2 glb_lava4_itemtypelist[] =
{
	{ 5, 6, ITEMTYPE_ARTIFACT },
	{ -1, -1, ITEMTYPE_NONE }
};

const PT2 glb_lava4_moblevellist[] =
{
	{ 5, 6, MOBLEVEL_UNIQUE },
	{ -1, -1, MOBLEVEL_NONE }
};

const PT2 glb_lava4_intrinsiclist[] =
{
	{ 5, 6, INTRINSIC_LEADER },
	{ -1, -1, INTRINSIC_NONE }
};

const PT2 glb_lava4_squareflaglist[] =
{
	{ 5, 6, SQUAREFLAG_LIT },
	{ 4, 6, SQUAREFLAG_LIT },
	{ 3, 6, SQUAREFLAG_LIT },
	{ 6, 5, SQUAREFLAG_LIT },
	{ 5, 5, SQUAREFLAG_LIT },
	{ 4, 5, SQUAREFLAG_LIT },
	{ 3, 5, SQUAREFLAG_LIT },
	{ 2, 5, SQUAREFLAG_LIT },
	{ 1, 5, SQUAREFLAG_LIT },
	{ 5, 4, SQUAREFLAG_LIT },
	{ 4, 4, SQUAREFLAG_LIT },
	{ 3, 4, SQUAREFLAG_LIT },
	{ 2, 4, SQUAREFLAG_LIT },
	{ 1, 4, SQUAREFLAG_LIT },
	{ 6, 3, SQUAREFLAG_LIT },
	{ 5, 3, SQUAREFLAG_LIT },
	{ 4, 3, SQUAREFLAG_LIT },
	{ 4, 2, SQUAREFLAG_LIT },
	{ 2, 2, SQUAREFLAG_LIT },
	{ 1, 2, SQUAREFLAG_LIT },
	{ 0, 2, SQUAREFLAG_LIT },
	{ 7, 1, SQUAREFLAG_LIT },
	{ 6, 1, SQUAREFLAG_LIT },
	{ 5, 1, SQUAREFLAG_LIT },
	{ 4, 1, SQUAREFLAG_LIT },
	{ 3, 1, SQUAREFLAG_LIT },
	{ 2, 1, SQUAREFLAG_LIT },
	{ 3, 0, SQUAREFLAG_LIT },
	{ -1, -1, SQUAREFLAG_NONE }
};

const PT2 glb_lava4_signpostlist[] =
{
	{ -1, -1, SIGNPOST_NONE }
};

const ROOM_DEF glb_lava4_roomdef =
{
	{ 8, 8, 0 },
	glb_lava4_squarelist,
	glb_lava4_squareflaglist,
	glb_lava4_itemlist,
	glb_lava4_moblist,
	glb_lava4_itemtypelist,
	glb_lava4_moblevellist,
	glb_lava4_intrinsiclist,
	glb_lava4_signpostlist,
	6, -1,
	100,
	0, 0,
	0,
	1,
	1,
	1,
	1,
	-1, -1, 
	-1, 
	"lava4"
};
