// Auto-generated .map file
// DO NOT HAND EDIT
// Generated from slug.map

#include "../map.h"
#include "../glbdef.h"

const SQUARE_NAMES glb_slug_squarelist[] =
{
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_BLOCKEDDOOR,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_BLOCKEDDOOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_EMPTY,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_ACID,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_ACID,	SQUARE_ACID,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_ACID,	SQUARE_ACID,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_BLOCKEDDOOR,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	
SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_CORRIDOR,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY,	
SQUARE_EMPTY,	SQUARE_EMPTY,	SQUARE_EMPTY
};

const PT2 glb_slug_moblist[] =
{
	{ 7, 7, MOB_BROWNSLUG },
	{ 8, 6, MOB_DEATHSLUG },
	{ 2, 6, MOB_DEATHSLUG },
	{ 8, 5, MOB_PURPLESLUG },
	{ 1, 5, MOB_DEATHSLUG },
	{ 8, 3, MOB_DEATHSLUG },
	{ 2, 3, MOB_PURPLESLUG },
	{ 9, 2, MOB_PURPLESLUG },
	{ 4, 2, MOB_DEATHSLUG },
	{ 7, 1, MOB_BROWNSLUG },
	{ 2, 1, MOB_BROWNSLUG },
	{ -1, -1, MOB_NONE }
};

const PT2 glb_slug_itemlist[] =
{
	{ -1, -1, ITEM_NONE }
};

const PT2 glb_slug_itemtypelist[] =
{
	{ 1, 5, ITEMTYPE_ARTIFACT },
	{ -1, -1, ITEMTYPE_NONE }
};

const PT2 glb_slug_moblevellist[] =
{
	{ 1, 5, MOBLEVEL_UNIQUE },
	{ -1, -1, MOBLEVEL_NONE }
};

const PT2 glb_slug_intrinsiclist[] =
{
	{ -1, -1, INTRINSIC_NONE }
};

const PT2 glb_slug_squareflaglist[] =
{
	{ 10, 8, SQUAREFLAG_LIT },
	{ 9, 8, SQUAREFLAG_LIT },
	{ 8, 8, SQUAREFLAG_LIT },
	{ 7, 8, SQUAREFLAG_LIT },
	{ 6, 8, SQUAREFLAG_LIT },
	{ 5, 8, SQUAREFLAG_LIT },
	{ 4, 8, SQUAREFLAG_LIT },
	{ 3, 8, SQUAREFLAG_LIT },
	{ 2, 8, SQUAREFLAG_LIT },
	{ 1, 8, SQUAREFLAG_LIT },
	{ 0, 8, SQUAREFLAG_LIT },
	{ 10, 7, SQUAREFLAG_LIT },
	{ 9, 7, SQUAREFLAG_LIT },
	{ 8, 7, SQUAREFLAG_LIT },
	{ 7, 7, SQUAREFLAG_LIT },
	{ 6, 7, SQUAREFLAG_LIT },
	{ 5, 7, SQUAREFLAG_LIT },
	{ 4, 7, SQUAREFLAG_LIT },
	{ 3, 7, SQUAREFLAG_LIT },
	{ 2, 7, SQUAREFLAG_LIT },
	{ 1, 7, SQUAREFLAG_LIT },
	{ 0, 7, SQUAREFLAG_LIT },
	{ 10, 6, SQUAREFLAG_LIT },
	{ 9, 6, SQUAREFLAG_LIT },
	{ 8, 6, SQUAREFLAG_LIT },
	{ 7, 6, SQUAREFLAG_LIT },
	{ 6, 6, SQUAREFLAG_LIT },
	{ 5, 6, SQUAREFLAG_LIT },
	{ 4, 6, SQUAREFLAG_LIT },
	{ 3, 6, SQUAREFLAG_LIT },
	{ 2, 6, SQUAREFLAG_LIT },
	{ 1, 6, SQUAREFLAG_LIT },
	{ 0, 6, SQUAREFLAG_LIT },
	{ 10, 5, SQUAREFLAG_LIT },
	{ 9, 5, SQUAREFLAG_LIT },
	{ 8, 5, SQUAREFLAG_LIT },
	{ 7, 5, SQUAREFLAG_LIT },
	{ 6, 5, SQUAREFLAG_LIT },
	{ 5, 5, SQUAREFLAG_LIT },
	{ 4, 5, SQUAREFLAG_LIT },
	{ 3, 5, SQUAREFLAG_LIT },
	{ 2, 5, SQUAREFLAG_LIT },
	{ 1, 5, SQUAREFLAG_LIT },
	{ 0, 5, SQUAREFLAG_LIT },
	{ 10, 4, SQUAREFLAG_LIT },
	{ 9, 4, SQUAREFLAG_LIT },
	{ 8, 4, SQUAREFLAG_LIT },
	{ 7, 4, SQUAREFLAG_LIT },
	{ 6, 4, SQUAREFLAG_LIT },
	{ 5, 4, SQUAREFLAG_LIT },
	{ 4, 4, SQUAREFLAG_LIT },
	{ 3, 4, SQUAREFLAG_LIT },
	{ 2, 4, SQUAREFLAG_LIT },
	{ 1, 4, SQUAREFLAG_LIT },
	{ 0, 4, SQUAREFLAG_LIT },
	{ 10, 3, SQUAREFLAG_LIT },
	{ 9, 3, SQUAREFLAG_LIT },
	{ 8, 3, SQUAREFLAG_LIT },
	{ 7, 3, SQUAREFLAG_LIT },
	{ 6, 3, SQUAREFLAG_LIT },
	{ 5, 3, SQUAREFLAG_LIT },
	{ 4, 3, SQUAREFLAG_LIT },
	{ 3, 3, SQUAREFLAG_LIT },
	{ 2, 3, SQUAREFLAG_LIT },
	{ 1, 3, SQUAREFLAG_LIT },
	{ 0, 3, SQUAREFLAG_LIT },
	{ 10, 2, SQUAREFLAG_LIT },
	{ 9, 2, SQUAREFLAG_LIT },
	{ 8, 2, SQUAREFLAG_LIT },
	{ 7, 2, SQUAREFLAG_LIT },
	{ 6, 2, SQUAREFLAG_LIT },
	{ 5, 2, SQUAREFLAG_LIT },
	{ 4, 2, SQUAREFLAG_LIT },
	{ 3, 2, SQUAREFLAG_LIT },
	{ 2, 2, SQUAREFLAG_LIT },
	{ 1, 2, SQUAREFLAG_LIT },
	{ 0, 2, SQUAREFLAG_LIT },
	{ 10, 1, SQUAREFLAG_LIT },
	{ 9, 1, SQUAREFLAG_LIT },
	{ 8, 1, SQUAREFLAG_LIT },
	{ 7, 1, SQUAREFLAG_LIT },
	{ 6, 1, SQUAREFLAG_LIT },
	{ 5, 1, SQUAREFLAG_LIT },
	{ 4, 1, SQUAREFLAG_LIT },
	{ 3, 1, SQUAREFLAG_LIT },
	{ 2, 1, SQUAREFLAG_LIT },
	{ 1, 1, SQUAREFLAG_LIT },
	{ 0, 1, SQUAREFLAG_LIT },
	{ 10, 0, SQUAREFLAG_LIT },
	{ 9, 0, SQUAREFLAG_LIT },
	{ 8, 0, SQUAREFLAG_LIT },
	{ 7, 0, SQUAREFLAG_LIT },
	{ 6, 0, SQUAREFLAG_LIT },
	{ 5, 0, SQUAREFLAG_LIT },
	{ 4, 0, SQUAREFLAG_LIT },
	{ 3, 0, SQUAREFLAG_LIT },
	{ 2, 0, SQUAREFLAG_LIT },
	{ 1, 0, SQUAREFLAG_LIT },
	{ 0, 0, SQUAREFLAG_LIT },
	{ -1, -1, SQUAREFLAG_NONE }
};

const PT2 glb_slug_signpostlist[] =
{
	{ -1, -1, SIGNPOST_NONE }
};

const ROOM_DEF glb_slug_roomdef =
{
	{ 11, 9, 0 },
	glb_slug_squarelist,
	glb_slug_squareflaglist,
	glb_slug_itemlist,
	glb_slug_moblist,
	glb_slug_itemtypelist,
	glb_slug_moblevellist,
	glb_slug_intrinsiclist,
	glb_slug_signpostlist,
	6, -1,
	100,
	0, 0,
	0,
	1,
	1,
	1,
	1,
	-1, -1, 
	-1, 
	"slug"
};
