// Auto-generated .map file
// DO NOT HAND EDIT
// Generated from temple.map

#include "../map.h"
#include "../glbdef.h"

const SQUARE_NAMES glb_temple_squarelist[] =
{
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_FLOOR,	
SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_FLOOR,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_WALL,	
SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_WALL,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_BLOCKEDDOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_BLOCKEDDOOR,	
SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_WALL,	SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	SQUARE_FLOOR,	
SQUARE_FLOOR,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_BLOCKEDDOOR,	
SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	SQUARE_WALL,	
SQUARE_WALL
};

const PT2 glb_temple_moblist[] =
{
	{ 7, 2, MOB_KOBOLD },
	{ 5, 2, MOB_KOBOLD },
	{ 3, 2, MOB_KOBOLD },
	{ 6, 1, MOB_KOBOLDMAGE },
	{ 4, 1, MOB_KOBOLDMAGE },
	{ -1, -1, MOB_NONE }
};

const PT2 glb_temple_itemlist[] =
{
	{ -1, -1, ITEM_NONE }
};

const PT2 glb_temple_itemtypelist[] =
{
	{ 9, 5, ITEMTYPE_WEAPON },
	{ 1, 5, ITEMTYPE_ARMOUR },
	{ 5, 1, ITEMTYPE_AMULET },
	{ -1, -1, ITEMTYPE_NONE }
};

const PT2 glb_temple_moblevellist[] =
{
	{ -1, -1, MOBLEVEL_NONE }
};

const PT2 glb_temple_intrinsiclist[] =
{
	{ 4, 1, INTRINSIC_LEADER },
	{ -1, -1, INTRINSIC_NONE }
};

const PT2 glb_temple_squareflaglist[] =
{
	{ 10, 10, SQUAREFLAG_LIT },
	{ 9, 10, SQUAREFLAG_LIT },
	{ 8, 10, SQUAREFLAG_LIT },
	{ 7, 10, SQUAREFLAG_LIT },
	{ 6, 10, SQUAREFLAG_LIT },
	{ 5, 10, SQUAREFLAG_LIT },
	{ 4, 10, SQUAREFLAG_LIT },
	{ 3, 10, SQUAREFLAG_LIT },
	{ 2, 10, SQUAREFLAG_LIT },
	{ 1, 10, SQUAREFLAG_LIT },
	{ 0, 10, SQUAREFLAG_LIT },
	{ 10, 9, SQUAREFLAG_LIT },
	{ 9, 9, SQUAREFLAG_LIT },
	{ 8, 9, SQUAREFLAG_LIT },
	{ 7, 9, SQUAREFLAG_LIT },
	{ 6, 9, SQUAREFLAG_LIT },
	{ 5, 9, SQUAREFLAG_LIT },
	{ 4, 9, SQUAREFLAG_LIT },
	{ 3, 9, SQUAREFLAG_LIT },
	{ 2, 9, SQUAREFLAG_LIT },
	{ 1, 9, SQUAREFLAG_LIT },
	{ 0, 9, SQUAREFLAG_LIT },
	{ 10, 8, SQUAREFLAG_LIT },
	{ 9, 8, SQUAREFLAG_LIT },
	{ 8, 8, SQUAREFLAG_LIT },
	{ 7, 8, SQUAREFLAG_LIT },
	{ 6, 8, SQUAREFLAG_LIT },
	{ 5, 8, SQUAREFLAG_LIT },
	{ 4, 8, SQUAREFLAG_LIT },
	{ 3, 8, SQUAREFLAG_LIT },
	{ 2, 8, SQUAREFLAG_LIT },
	{ 1, 8, SQUAREFLAG_LIT },
	{ 0, 8, SQUAREFLAG_LIT },
	{ 10, 7, SQUAREFLAG_LIT },
	{ 9, 7, SQUAREFLAG_LIT },
	{ 8, 7, SQUAREFLAG_LIT },
	{ 7, 7, SQUAREFLAG_LIT },
	{ 6, 7, SQUAREFLAG_LIT },
	{ 5, 7, SQUAREFLAG_LIT },
	{ 4, 7, SQUAREFLAG_LIT },
	{ 3, 7, SQUAREFLAG_LIT },
	{ 2, 7, SQUAREFLAG_LIT },
	{ 1, 7, SQUAREFLAG_LIT },
	{ 0, 7, SQUAREFLAG_LIT },
	{ 10, 6, SQUAREFLAG_LIT },
	{ 9, 6, SQUAREFLAG_LIT },
	{ 8, 6, SQUAREFLAG_LIT },
	{ 7, 6, SQUAREFLAG_LIT },
	{ 6, 6, SQUAREFLAG_LIT },
	{ 5, 6, SQUAREFLAG_LIT },
	{ 4, 6, SQUAREFLAG_LIT },
	{ 3, 6, SQUAREFLAG_LIT },
	{ 2, 6, SQUAREFLAG_LIT },
	{ 1, 6, SQUAREFLAG_LIT },
	{ 0, 6, SQUAREFLAG_LIT },
	{ 10, 5, SQUAREFLAG_LIT },
	{ 9, 5, SQUAREFLAG_LIT },
	{ 8, 5, SQUAREFLAG_LIT },
	{ 7, 5, SQUAREFLAG_LIT },
	{ 6, 5, SQUAREFLAG_LIT },
	{ 5, 5, SQUAREFLAG_LIT },
	{ 4, 5, SQUAREFLAG_LIT },
	{ 3, 5, SQUAREFLAG_LIT },
	{ 2, 5, SQUAREFLAG_LIT },
	{ 1, 5, SQUAREFLAG_LIT },
	{ 0, 5, SQUAREFLAG_LIT },
	{ 10, 4, SQUAREFLAG_LIT },
	{ 9, 4, SQUAREFLAG_LIT },
	{ 8, 4, SQUAREFLAG_LIT },
	{ 7, 4, SQUAREFLAG_LIT },
	{ 6, 4, SQUAREFLAG_LIT },
	{ 5, 4, SQUAREFLAG_LIT },
	{ 4, 4, SQUAREFLAG_LIT },
	{ 3, 4, SQUAREFLAG_LIT },
	{ 2, 4, SQUAREFLAG_LIT },
	{ 1, 4, SQUAREFLAG_LIT },
	{ 0, 4, SQUAREFLAG_LIT },
	{ 10, 3, SQUAREFLAG_LIT },
	{ 9, 3, SQUAREFLAG_LIT },
	{ 8, 3, SQUAREFLAG_LIT },
	{ 7, 3, SQUAREFLAG_LIT },
	{ 6, 3, SQUAREFLAG_LIT },
	{ 5, 3, SQUAREFLAG_LIT },
	{ 4, 3, SQUAREFLAG_LIT },
	{ 3, 3, SQUAREFLAG_LIT },
	{ 2, 3, SQUAREFLAG_LIT },
	{ 1, 3, SQUAREFLAG_LIT },
	{ 0, 3, SQUAREFLAG_LIT },
	{ 10, 2, SQUAREFLAG_LIT },
	{ 9, 2, SQUAREFLAG_LIT },
	{ 8, 2, SQUAREFLAG_LIT },
	{ 7, 2, SQUAREFLAG_LIT },
	{ 6, 2, SQUAREFLAG_LIT },
	{ 5, 2, SQUAREFLAG_LIT },
	{ 4, 2, SQUAREFLAG_LIT },
	{ 3, 2, SQUAREFLAG_LIT },
	{ 2, 2, SQUAREFLAG_LIT },
	{ 1, 2, SQUAREFLAG_LIT },
	{ 0, 2, SQUAREFLAG_LIT },
	{ 10, 1, SQUAREFLAG_LIT },
	{ 9, 1, SQUAREFLAG_LIT },
	{ 8, 1, SQUAREFLAG_LIT },
	{ 7, 1, SQUAREFLAG_LIT },
	{ 6, 1, SQUAREFLAG_LIT },
	{ 5, 1, SQUAREFLAG_LIT },
	{ 4, 1, SQUAREFLAG_LIT },
	{ 3, 1, SQUAREFLAG_LIT },
	{ 2, 1, SQUAREFLAG_LIT },
	{ 1, 1, SQUAREFLAG_LIT },
	{ 0, 1, SQUAREFLAG_LIT },
	{ 10, 0, SQUAREFLAG_LIT },
	{ 9, 0, SQUAREFLAG_LIT },
	{ 8, 0, SQUAREFLAG_LIT },
	{ 7, 0, SQUAREFLAG_LIT },
	{ 6, 0, SQUAREFLAG_LIT },
	{ 5, 0, SQUAREFLAG_LIT },
	{ 4, 0, SQUAREFLAG_LIT },
	{ 3, 0, SQUAREFLAG_LIT },
	{ 2, 0, SQUAREFLAG_LIT },
	{ 1, 0, SQUAREFLAG_LIT },
	{ 0, 0, SQUAREFLAG_LIT },
	{ -1, -1, SQUAREFLAG_NONE }
};

const PT2 glb_temple_signpostlist[] =
{
	{ -1, -1, SIGNPOST_NONE }
};

const ROOM_DEF glb_temple_roomdef =
{
	{ 11, 11, 0 },
	glb_temple_squarelist,
	glb_temple_squareflaglist,
	glb_temple_itemlist,
	glb_temple_moblist,
	glb_temple_itemtypelist,
	glb_temple_moblevellist,
	glb_temple_intrinsiclist,
	glb_temple_signpostlist,
	3, -1,
	100,
	0, 0,
	0,
	1,
	1,
	1,
	1,
	-1, -1, 
	-1, 
	"temple"
};
